server:
  port: 0808

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guavadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: boss

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: banarasi
      password: banarasi


#  spring.mail.properties.mail.smtp.ssl.protocols : TLSv1.2
#  spring.mail.host : smtp.gmail.com
#  spring.mail.port : 587
#  spring.mail.username : ${Email}
#  spring.mail.password : ${Password}
#  spring.mail.properties.mail.smtp.auths : true
#  spring.mail.properties.mail.smtp.starttls.enable : true